# Generated by Django 2.2.8 on 2019-12-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
